name: Q1 Workflow
on:
  push:
    paths:
      - README.md

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Copy README.md to Q1_archive_README.md
        run: |
          cp README.md Q1_archive_README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Q1_archive_README.md
          git commit -m "Added Q1_archive_README.md" || echo "No changes to commit"
          git pull --rebase
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Raspya/R5-09-DS.git
