name: Copier README dans Q1_archive_README

on:
  push:
    paths:
      - README.md  # Le workflow se déclenche uniquement si le fichier README.md est modifié

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

     - name: Copier README.md vers Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Récupérer les dernières modifications du dépôt distant
        run: git pull origin HEAD

      - name: Ajouter et pousser les changements
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Q1_archive_README.md
          git commit -m "Ajout de Q1_archive_README.md"
          git push origin HEAD 